#!/bin/bash

echo "coder:$PASSWORD" | chpasswd
# [[ -d '/home/coder/.oh-my-zsh' ]] || runuser -l coder -c 'sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"' 
exec /usr/sbin/sshd -D -e
